CREATE SCHEMA IF NOT EXISTS cbr;
GRANT ALL PRIVILEGES ON DATABASE cbr TO usr;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA cbr TO usr;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA cbr TO usr;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA cbr TO usr;
