--liquibase formatted sql
--changeset alex4790354:01_002


INSERT INTO cbr.currency(id, frequency, nominal, instr_name, instr_name_eng, name_eng, name_rus)
 VALUES('R01230' , 'DAILY', 10    , 'Официальный курс AED/RUB', 'AEDRUB Official Rate', 'UAE Dirham'               , 'Дирхам ОАЭ'),
       ('R01060' , 'DAILY', 1000  , 'Официальный курс AMD/RUB', 'AMDRUB Official Rate', 'Armenia Dram'             , 'Армянский драм'),
       ('R01010' , 'DAILY', 1     , 'Официальный курс AUD/RUB', 'AUDRUB Official Rate', 'Australian Dollar'        , 'Австралийский доллар'),
       ('R01020A', 'DAILY', 1     , 'Официальный курс AZN/RUB', 'AZNRUB Official Rate', 'Azerbaijan Manat'         , 'Азербайджанский манат'),
       ('R01100' , 'DAILY', 1     , 'Официальный курс BGN/RUB', 'BGNRUB Official Rate', 'Bulgarian lev'            , 'Болгарский лев'),
       ('R01115' , 'DAILY', 1     , 'Официальный курс BRL/RUB', 'BRLRUB Official Rate', 'Brazil Real'              , 'Бразильский реал'),
       ('R01090B', 'DAILY', 1     , 'Официальный курс BYN/RUB', 'BYNRUB Official Rate', 'Belarussian Ruble'        , 'Белорусский рубль'),
       ('R01350' , 'DAILY', 1     , 'Официальный курс CAD/RUB', 'CADRUB Official Rate', 'Canadian Dollar'          , 'Канадский доллар'),
       ('R01775' , 'DAILY', 1     , 'Официальный курс CHF/RUB', 'CHFRUB Official Rate', 'Swiss Franc'              , 'Швейцарский франк'),
       ('R01375' , 'DAILY', 10    , 'Официальный курс CNY/RUB', 'CNYRUB Official Rate', 'China Yuan'               , 'Китайский юань'),
       ('R01760' , 'DAILY', 10    , 'Официальный курс CZK/RUB', 'CZKRUB Official Rate', 'Czech Koruna'             , 'Чешская крона'),
       ('R01215' , 'DAILY', 10    , 'Официальный курс DKK/RUB', 'DKKRUB Official Rate', 'Danish Krone'             , 'Датская крона'),
       ('R01240' , 'DAILY', 10    , 'Официальный курс EGP/RUB', 'EGPRUB Official Rate', 'Egyptian Pound'           , 'Египетский фунт'),
       ('R01239' , 'DAILY', 1     , 'Официальный курс EUR/RUB', 'EURRUB Official Rate', 'Euro'                     , 'Евро'),
       ('R01035' , 'DAILY', 1     , 'Официальный курс GBP/RUB', 'GBPRUB Official Rate', 'British Pound Sterling'   , 'Фунт стерлингов Соединенного королевства'),
       ('R01210' , 'DAILY', 1     , 'Официальный курс GEL/RUB', 'GELRUB Official Rate', 'Georgia Lari'             , 'Грузинский лари'),
       ('R01200' , 'DAILY', 10    , 'Официальный курс HKD/RUB', 'HKDRUB Official Rate', 'Hong Kong Dollar'         , 'Гонконгский доллар'),
       ('R01135' , 'DAILY', 100   , 'Официальный курс HUF/RUB', 'HUFRUB Official Rate', 'Hungarian Forint'         , 'Венгерский форинт'),
       ('R01280' , 'DAILY', 10000 , 'Официальный курс IDR/RUB', 'IDRRUB Official Rate', 'Indonesian Rupiah'        , 'Индонезийская рупия'),
       ('R01270' , 'DAILY', 100   , 'Официальный курс INR/RUB', 'INRRUB Official Rate', 'Indian Rupee'             , 'Индийская рупия'),
       ('R01820' , 'DAILY', 100   , 'Официальный курс JPY/RUB', 'JPYRUB Official Rate', 'Japanese Yen'             , 'Японская иена'),
       ('R01370' , 'DAILY', 100   , 'Официальный курс KGS/RUB', 'KGSRUB Official Rate', 'Kyrgyzstan Som'           , 'Киргизский сом'),
       ('R01815' , 'DAILY', 1000  , 'Официальный курс KRW/RUB', 'KRWRUB Official Rate', 'South Korean Won'         , 'Вон Республики Корея'),
       ('R01335' , 'DAILY', 100   , 'Официальный курс KZT/RUB', 'KZTRUB Official Rate', 'Kazakhstan Tenge'         , 'Казахстанский тенге'),
       ('R01500' , 'DAILY', 10    , 'Официальный курс MDL/RUB', 'MDLRUB Official Rate', 'Moldova Lei'              , 'Молдавский лей'),
       ('R01535' , 'DAILY', 10    , 'Официальный курс NOK/RUB', 'NOKRUB Official Rate', 'Norwegian Krone'          , 'Норвежская крона'),
       ('R01530' , 'DAILY', 1     , 'Официальный курс NZD/RUB', 'NZDRUB Official Rate', 'New Zealand Dollar'       , 'Новозеландский доллар'),
       ('R01565' , 'DAILY', 1     , 'Официальный курс PLN/RUB', 'PLNRUB Official Rate', 'Polish Zloty'             , 'Польский злотый'),
       ('R01355' , 'DAILY', 10    , 'Официальный курс QAR/RUB', 'QARRUB Official Rate', 'Qatari Riyal'             , 'Катарский риал'),
       ('R01585' , 'DAILY', 10000 , 'Официальный курс RON/RUB', 'RONRUB Official Rate', 'Romanian Leu'             , 'Румынский лей'),
       ('R01585F', 'DAILY', 10    , 'Официальный курс RON/RUB', 'RONRUB Official Rate', 'Romanian Leu'             , 'Румынский лей'),
       ('R01805F', 'DAILY', 100   , 'Официальный курс RSD/RUB', 'RSDRUB Official Rate', 'Serbian Dinar'            , 'Сербский динар'),
       ('R01770' , 'DAILY', 10    , 'Официальный курс SEK/RUB', 'SEKRUB Official Rate', 'Swedish Krona'            , 'Шведская крона'),
       ('R01625' , 'DAILY', 1     , 'Официальный курс SGD/RUB', 'SGDRUB Official Rate', 'Singapore Dollar'         , 'Сингапурский доллар'),
       ('R01675' , 'DAILY', 100   , 'Официальный курс THB/RUB', 'THBRUB Official Rate', 'Thai Baht'                , 'Таиландский бат'),
       ('R01670' , 'DAILY', 10    , 'Официальный курс TJS/RUB', 'TJSRUB Official Rate', 'Tajikistan Ruble'         , 'Таджикский сомони'),
       ('R01710A', 'DAILY', 1     , 'Официальный курс TMT/RUB', 'TMTRUB Official Rate', 'New Turkmenistan Manat'   , 'Новый туркменский манат'),
       ('R01700J', 'DAILY', 1     , 'Официальный курс TRY/RUB', 'TRYRUB Official Rate', 'Turkish Lira'             , 'Турецкая лира'),
       ('R01720' , 'DAILY', 10    , 'Официальный курс UAH/RUB', 'UAHRUB Official Rate', 'Ukrainian Hryvnia'        , 'Украинская гривна'),
       ('R01235' , 'DAILY', 1     , 'Официальный курс USD/RUB', 'USDRUB Official Rate', 'US Dollar'                , 'Доллар США'),
       ('R01717' , 'DAILY', 1000  , 'Официальный курс UZS/RUB', 'UZSRUB Official Rate', 'Uzbekistan Sum'           , 'Узбекский сум'),
       ('R01150' , 'DAILY', 10000 , 'Официальный курс VND/RUB', 'VNDRUB Official Rate', 'Vietnam Dong'             , 'Вьетнамский донг'),
       ('R01589' , 'DAILY', 1     , 'Официальный курс XDR/RUB', 'XDRRUB Official Rate', 'SDR'                      , 'СДР (специальные права заимствования)'),
       ('R01810' , 'DAILY', 10    , 'Официальный курс ZAR/RUB', 'ZARRUB Official Rate', 'S.African Rand'           , 'Южноафриканский рэнд');
